# docker compose --profile omnet_network build
# docker compose --profile omnet_network up
# docker compose --profile zero_delay_network build
# docker compose --profile zero_delay_network up

version: '3.9'

services:
  tod-carla:
    #depends_on: 
    #  - carla_simulator
    build: tod-carla/
    volumes:
      - type: bind
        source: ./tod-carla/configuration
        target: /app/tod-carla/configuration
        read_only: true
      - ./results/carla:/app/tod-carla/out
    #ports:
      #- 5555:5555
    environment:
      - simulator_configuration_file_path=configuration/simulator/docker.yaml

  carla-simulator:
    #image: carlasim/carla:0.9.13
    build: .

    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 2000-2002:2000-2002
      - 4242:4242
    #command:  ./CarlaUE4.sh -RenderOffScreen
  
  tod-omnet:
    #depends_on: 
    #  - tod_simulator
    build: tod-omnet
    volumes:
      - type: bind
        source: ./tod-omnet/simulations
        target: /app/tod-omnet/simulations
        read_only: true
      - ./results/omnet:/app/tod-omnet/results

    profiles:
      - omnet_network

   
  zero-delay-network:
    #depends_on: 
    #  - tod_simulator
    build: 
      context: zero_delay_network
      args:
        seeds: 1000 2000 3000 4000 5000 6000 # change here seeds
    profiles:
      - zero_delay_network
