# docker compose --profile omnet_network build
# docker compose --profile omnet_network up
# docker compose --profile zero_delay_network build
# docker compose --profile zero_delay_network up

version: '3.9'

services:
  tod_simulator:
    #depends_on: 
    #  - carla_simulator
    build: tod_simulator/
    volumes:
      - type: bind
        source: ./tod_simulator/configuration
        target: /app/tod_simulator/configuration
        read_only: true
      - ./results/carla:/app/tod_simulator/out
    #ports:
      #- 5555:5555
    environment:
      - simulator_configuration_file_path=configuration/simulator/docker.yaml

  carla_simulator:
    #image: carlasim/carla:0.9.13
    build: .

    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 2000-2002:2000-2002
      - 4242:4242
    #command:  ./CarlaUE4.sh -RenderOffScreen
  
  tod_omnet_network:
    #depends_on: 
    #  - tod_simulator
    build: tod_omnet_network
    volumes:
      - type: bind
        source: ./tod_omnet_network/simulations
        target: /app/tod_omnet_network/simulations
        read_only: true
      - ./results/omnet:/app/tod_omnet_network/results

    profiles:
      - omnet_network

   
  zero_delay_network:
    #depends_on: 
    #  - tod_simulator
    build: 
      context: zero_delay_network
      args:
        seeds: 1000 2000 3000 4000 5000 6000 # change here seeds
    profiles:
      - zero_delay_network
